Repository DS-AEON/back-end, pull requests merged in 2024-05, with the labels that each got.

#20 User/login Test코드 추가 및 auth 방식 변경
  build.gradle
  src/main/java/com/aeon/hadog/base/code/ErrorCode.java
  src/main/java/com/aeon/hadog/base/exception/GlobalExceptionHandler.java
  src/main/java/com/aeon/hadog/base/exception/NewPasswordSameAsOldException.java
  src/main/java/com/aeon/hadog/base/exception/PasswordFormatInvalidException.java
  src/main/java/com/aeon/hadog/controller/UserController.java
  src/main/java/com/aeon/hadog/domain/Emotion.java
  src/main/java/com/aeon/hadog/repository/UserRepository.java
  src/main/java/com/aeon/hadog/service/UserService.java
  src/test/java/com/aeon/hadog/controller/UserControllerTest.java
  src/test/java/com/aeon/hadog/service/UserServiceTest.java
  src/test/resources/application-test.properties
Labels: ✅ Test, 🔨 Refactor

#25 Feat: Amazon S3 연결
  .gitignore
  build.gradle
  src/main/java/com/aeon/hadog/base/config/aws/AwsS3Config.java
  src/main/java/com/aeon/hadog/base/dto/PetDTO.java
  src/main/java/com/aeon/hadog/base/dto/pet/PetDTO.java
  src/main/java/com/aeon/hadog/controller/PetController.java
  src/main/java/com/aeon/hadog/domain/Pet.java
  src/main/java/com/aeon/hadog/service/AmazonS3Service.java
  src/main/java/com/aeon/hadog/service/PetService.java
  src/test/java/com/aeon/hadog/controller/PetControllerTest.java
  src/test/java/com/aeon/hadog/service/PetServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#26 Diary 작성, 상세, 수정 기능 추가
  src/main/java/com/aeon/hadog/base/code/ErrorCode.java
  src/main/java/com/aeon/hadog/base/dto/diary/DiaryDTO.java
  src/main/java/com/aeon/hadog/base/exception/BlanckContentException.java
  src/main/java/com/aeon/hadog/base/exception/DiaryNotFoundException.java
  src/main/java/com/aeon/hadog/base/exception/EmotionTrackNotBelongToUserException.java
  src/main/java/com/aeon/hadog/base/exception/EmotionTrackNotFoundException.java
  src/main/java/com/aeon/hadog/base/exception/GlobalExceptionHandler.java
  src/main/java/com/aeon/hadog/controller/DiaryController.java
  src/main/java/com/aeon/hadog/domain/Diary.java
  src/main/java/com/aeon/hadog/domain/EmotionTrack.java
  src/main/java/com/aeon/hadog/repository/DiaryRepository.java
  src/main/java/com/aeon/hadog/repository/EmotionTrackRepository.java
  src/main/java/com/aeon/hadog/repository/PetRepository.java
  src/main/java/com/aeon/hadog/service/DiaryService.java
Labels: ✨ Feature

#33 Refactor: Pet 오류처리
  src/main/java/com/aeon/hadog/base/code/ErrorCode.java
  src/main/java/com/aeon/hadog/base/exception/PetIdNotFoundException.java
  src/main/java/com/aeon/hadog/controller/PetController.java
  src/main/java/com/aeon/hadog/service/PetService.java
Labels: 🔨 Refactor

#30 Diary Entity/Service Refacor 및 목록 기능 추가
  src/main/java/com/aeon/hadog/controller/DiaryController.java
  src/main/java/com/aeon/hadog/domain/Diary.java
  src/main/java/com/aeon/hadog/repository/DiaryRepository.java
  src/main/java/com/aeon/hadog/service/DiaryService.java
Labels: ✨ Feature, 🔨 Refactor

#34 Refactor: 반려견 테스트 코드 수정
  src/test/java/com/aeon/hadog/controller/PetControllerTest.java
  src/test/java/com/aeon/hadog/service/PetServiceTest.java
Labels: ✅ Test

#38 Shelter 작성, 상세, 목록 기능 구현
  src/main/java/com/aeon/hadog/base/code/ErrorCode.java
  src/main/java/com/aeon/hadog/base/config/security/SecurityConfiguration.java
  src/main/java/com/aeon/hadog/base/dto/shelter/ListShelterPostDTO.java
  src/main/java/com/aeon/hadog/base/dto/shelter/ShelterPostDTO.java
  src/main/java/com/aeon/hadog/base/exception/GlobalExceptionHandler.java
  src/main/java/com/aeon/hadog/base/exception/ShelterPostNotFoundException.java
  src/main/java/com/aeon/hadog/controller/ShelterPostController.java
  src/main/java/com/aeon/hadog/domain/ShelterPostImages.java
  src/main/java/com/aeon/hadog/repository/ShelterPostImagesRepository.java
  src/main/java/com/aeon/hadog/repository/ShelterPostRepository.java
  src/main/java/com/aeon/hadog/service/AmazonS3Service.java
  src/main/java/com/aeon/hadog/service/ShelterPostService.java
Labels: ✨ Feature
