Repository DS-AEON/back-end, pull requests merged in 2024-07, with the labels that each got.

#31 FEAT: MyPage 내정보,반려견정보,닉네임반환
  build.gradle
  e -i HEAD~2
  src/main/java/com/aeon/hadog/base/config/security/SecurityConfiguration.java
  src/main/java/com/aeon/hadog/base/dto/MyPageDTO.java
  src/main/java/com/aeon/hadog/base/exception/GlobalExceptionHandler.java
  src/main/java/com/aeon/hadog/base/exception/PetNotFoundException.java
  src/main/java/com/aeon/hadog/controller/MyPageController.java
  src/main/java/com/aeon/hadog/repository/UserRepository.java
  src/main/java/com/aeon/hadog/service/MyPageService.java
Labels: ✨ Feature

#51 Feat: 대댓글 기능 수정 및 추가
  src/main/java/com/aeon/hadog/base/dto/comment/CommentDTO.java
  src/main/java/com/aeon/hadog/controller/CommentController.java
  src/main/java/com/aeon/hadog/service/ShelterPostCommentService.java
Labels: ✨ Feature, 🔨 Refactor

#63 Test/comment
  src/main/java/com/aeon/hadog/service/ShelterPostCommentService.java
  src/test/java/com/aeon/hadog/controller/CommentControllerTest.java
  src/test/java/com/aeon/hadog/service/ShelterPostCommentServiceTest.java
Labels: ✅ Test
